sudo: required
dist: trusty

language: python

env:
    global:
        - DISTUTILS_DEBUG=True

matrix:
    include:
        - python: "2.7"
        - python: "3.4"

install:
  - export PYVER=${TRAVIS_PYTHON_VERSION:0:1}
  # - pip install PyGObject
  - sudo apt-get install python-gi


script:
  - python setup.py install
  - python test/check_resources.py
