sudo: required
dist: xenial 

language: python

env:
    global:
        - DISTUTILS_DEBUG=True

notifications:
      email: false

matrix:
    include:
        - python: "3.4"


install:
  - sudo bash install_deps.sh 
  - python --version 
  - python setup.py install

script:
  - python test/check_resources.py
