sudo: required
dist: trusty

language: python

env:
    global:
        - DISTUTILS_DEBUG=True

notifications:
      email: false

matrix:
    include:
        # - python: "2.7"
        - python: "3.4"

install:
  - export PYVER=${TRAVIS_PYTHON_VERSION:0:1}
  - sudo bash install_deps.sh 
  - sudo bash pygobject.sh
  - sudo python3 setup.py install
  - python3 test/check_resources.py

#script:
#  - sudo bash pygobject.sh
#  - python setup.py install
#  - python test/check_resources.py
